@url_dev=http://localhost:3052/v1/api/

POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: abccccccaaxxxx

{
  "name": "Shop Tho",
  "email": "thonguyenvietit1@gmail.com",
  "password": "abc123"
}